/* Generated by re2c 1.1.1 on Wed Apr 22 13:17:52 2020 */
#line 1 "/home/clayton/projects/cMeta/lexer.re.c"
#include "lexer.h"
#include <assert.h>
#include "CMeta.h"
CMetaBuffer CMetaBufferInit(const char *fileName, int *errorCode)
{
  CMetaBuffer retVal;
  *errorCode=0;
  //
  FILE *file=fopen(fileName, "r");
  if(file==NULL)
    {
      *errorCode=1;
      return retVal;
    }
  fseek(file, 0, SEEK_END);
  size_t end=ftell(file);
  fseek(file, 0, SEEK_SET);
  size_t start=ftell(file);
  //
  char buffer[end-start+1];
  fread(buffer ,end-start, 1, file);
  buffer[end-start]='\0';
  sds source=sdsnew(buffer);
  fclose(file);
  //
  
  retVal.bufferPos=source;
  retVal.fileStart=source;
  retVal.fileEnd=source+sdslen(source);
  retVal.fileName=fileName;
  return retVal;
}
void CMetaBufferDestroy(CMetaBuffer *buffer)
{
  sdsfree((sds)buffer->fileStart);
}
void CMetaProccessString(CMetaBuffer *stringStart)
{
  const char *start=NULL,*end=NULL,*YYMARKER=NULL;
  
  const char *yyt1;
  
#line 46 "/home/clayton/projects/cMeta/lexer.c"
{
	char yych;
	yych = *stringStart->bufferPos;
	switch (yych) {
	case '"':
		yyt1 = stringStart->bufferPos;
		goto yy3;
	case '\'':
		yyt1 = stringStart->bufferPos;
		goto yy5;
	default:	goto yy2;
	}
yy2:
yy3:
	yych = *++stringStart->bufferPos;
	switch (yych) {
	case '"':	goto yy7;
	case '\\':	goto yy9;
	default:	goto yy3;
	}
yy5:
	yych = *++stringStart->bufferPos;
	switch (yych) {
	case '\'':	goto yy11;
	case '\\':	goto yy13;
	default:	goto yy5;
	}
yy7:
	++stringStart->bufferPos;
	start = yyt1;
	end = stringStart->bufferPos;
#line 51 "/home/clayton/projects/cMeta/lexer.re.c"
	{goto end;}
#line 80 "/home/clayton/projects/cMeta/lexer.c"
yy9:
	yych = *++stringStart->bufferPos;
	switch (yych) {
	case '\\':	goto yy9;
	default:	goto yy3;
	}
yy11:
	++stringStart->bufferPos;
	start = yyt1;
	end = stringStart->bufferPos;
#line 52 "/home/clayton/projects/cMeta/lexer.re.c"
	{goto end;}
#line 93 "/home/clayton/projects/cMeta/lexer.c"
yy13:
	yych = *++stringStart->bufferPos;
	switch (yych) {
	case '\\':	goto yy13;
	default:	goto yy5;
	}
}
#line 53 "/home/clayton/projects/cMeta/lexer.re.c"

    end:
  if(end==NULL)
    {
      printf("Incomplete string.");
      assert(end!=NULL);
    }
}
